using System;
using System.Linq;
using System.Text;
using FluentAPI;
using QFramework;
using Twenty2.VomitLib.Editor;
using UnityCodeGen;
using UnityEditor; // 如果是Unity环境，TypeCache通常在此命名空间
using UnityEngine; // 用于Debug.Log

[Generator]
public class AutoLoadGenerator : ICodeGenerator
{
    public void Execute(GeneratorContext context)
    {
        // 1. 设置生成路径
        context.OverrideFolderPath(VomitEditor.Config.CodeGenConfig.GenCodePath);

        // 2. 准备 StringBuilder
        StringBuilder sb = new StringBuilder();

        // 3. 获取并过滤类型
        var modelTypes = TypeCache.GetTypesDerivedFrom<AbstractModel>()
            .Where(t => !t.IsAbstract && !t.IsGenericTypeDefinition) // 排除抽象类和泛型未闭合类
            .OrderBy(t => t.FullName); // 排序以保持生成代码的一致性，减少Git冲突

        var systemTypes = TypeCache.GetTypesDerivedFrom<AbstractSystem>()
            .Where(t => !t.IsAbstract && !t.IsGenericTypeDefinition)
            .OrderBy(t => t.FullName);

        // 4. 开始构建文件内容
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 此代码由 AutoLoadGenerator 生成，请勿手动修改");
        sb.AppendLine("using System;");
        sb.AppendLine("");
        if (VomitEditor.Config.CodeGenConfig.GenCodeNamespace.IsNotNullAndEmpty())
        {
            sb.AppendLine("namespace Vomit.Generated");
            sb.AppendLine("{");
        }
        sb.AppendLine($"    public static class {VomitEditor.Config.CodeGenConfig.GenCodeClassName}");
        sb.AppendLine("    {");
        
        // 生成 AutoLoad 方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// [auto-generated] 依照合理的顺序关联框架的系统和数据");
        sb.AppendLine("        /// 替代原本的反射调用，性能更高");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void AutoLoad()");
        sb.AppendLine("        {");

        // 添加初始化检查 (对应反射代码中的 if(IsInit == false))
        sb.AppendLine("            if (Twenty2.VomitLib.Vomit.IsInit == false)");
        sb.AppendLine("            {");
        sb.AppendLine("                throw new Exception(\"请先调用 Vomit.Init(IArchitecture architecture)\");");
        sb.AppendLine("            }");
        sb.AppendLine("");
        sb.AppendLine("            var architecture = Twenty2.VomitLib.Vomit.Interface;");
        sb.AppendLine("");

        // 5. 生成 Model 注册代码
        sb.AppendLine("            // Register Models");
        foreach (var type in modelTypes)
        {
            // 使用 FullName 防止命名空间冲突
            // 生成: architecture.RegisterModel<Namespace.ClassName>(new Namespace.ClassName());
            string typeName = type.FullName.Replace('+', '.'); // 处理嵌套类的情况
            sb.AppendLine($"            architecture.RegisterModel<{typeName}>(new {typeName}());");
            // Debug.Log($"[CodeGen] Found Model: {typeName}");
        }
        
        sb.AppendLine("");

        // 6. 生成 System 注册代码
        sb.AppendLine("            // Register Systems");
        foreach (var type in systemTypes)
        {
            string typeName = type.FullName.Replace('+', '.');
            sb.AppendLine($"            architecture.RegisterSystem<{typeName}>(new {typeName}());");
            // Debug.Log($"[CodeGen] Found System: {typeName}");
        }

        sb.AppendLine("        }"); // End AutoLoad
        sb.AppendLine("    }");     // End Class
        if (VomitEditor.Config.CodeGenConfig.GenCodeNamespace.IsNotNullAndEmpty())
        {
            sb.AppendLine("}"); // End Namespace
        }

        // 7. 输出到文件
        context.AddCode($"{VomitEditor.Config.CodeGenConfig.GenCodeClassName}.cs", sb.ToString());
    }
}